### ISSUE TITLE
Possibility to add Query params in form of struct.

### ISSUE THREAD

**Issue by warik** [parnurzeal/gorequest#14]
Don'y You mind if i'll implement such thing?
Its pretty obvious to send struct as query params too, due to already existing possibility to do this with POST (sendStruct).
Why I'm asking - i have a structure which represents some parameters for GET request and what am i doing right now its marshalling data and sending them to Query function in form of string. And when Query unmarshalls it again. Its absolutely unnecessary overhead.
Of course i can concatenate this string in cycle - but it would be really shitty way.

So, what would You say?

**Comment by parnurzeal** [comment]
Hi @warik, how are you?
Wanna give it a try? Pull request is still welcome ;)

**Comment by figlief** [comment]
I  have done this in the features/add_query_from_structures branch of my fork of your repo github.com/figlief/gorequest

The problem is only capital first letters are allowed! for now  I lower case the  keys. Other alternatives?

I have done a simple cut and paste job, the common code should be factored out really.

I have refactored the  relavent bit of test code as the tests crash if the key is not found! very confusing and unhepfull.

Will do more work if you approve.

This is my first ever pull request , sorry If I screw it up.

**Comment by parnurzeal** [comment]
For now, it works. If we find more issue, let's fix it.
Thanks for your contribution. ;)

**Comment by seonixx** [comment]
Was this every actually implemented?
