### ISSUE TITLE
Text/plain

### ISSUE THREAD

**Issue by hunterboerner** [parnurzeal/gorequest#26]
I can't use text/plain with this library. It URL encodes what I send.

**Comment by parnurzeal** [comment]
Provide some example of your code would be very helpful for debugging :)
I will work on this soon.

**Comment by hunterboerner** [comment]
```
request := gorequest.New()
resp, body, errs := request.Post("http://example.com").
  Set("Content-Type","text/plain").
  Send(`Lorem ispum...`).
  End()
```

**Comment by smallnest** [comment]
I have added a new function that gorequest can send a raw string in post request body. It is useful that we can post a XML, marshalled string or any strings to servers. The default content type is "text/plain" but you can override ir by Set method.

There is a example:
```
gorequest.New().Post("http://requestb.in/19p19851") .Type("rawstr").
						Send(`Lorem ispum...`)
```
or 
```
gorequest.New().Post("http://requestb.in/19p19851") .
						SendRawString(`Lorem ispum...`)
	
```
There is the commit: commit 701548bc9c07051a9a0761ebfd42c30dfcf7d0bb.

I want feedback before start a pull request.

I think it can solve Issue #40, Issue #42, Issue #44 because you can set a a plain json string in body
