### ISSUE TITLE
Why the third return value is not error but []error?

### ISSUE THREAD

**Issue by beef9999** [parnurzeal/gorequest#78]
A single http request can have multiple errors?

**Comment by parnurzeal** [comment]
GoRequest is encapsulating a http request service and other additional useful functions that would help making http request an ease to the user.

So, the answer is "no, this is by design to giving the errors related to GoRequest itself and its functionalities not related to just a single http request."

**Comment by beef9999** [comment]
Could you provide some pest practice code about how to dealing with the errors? Make type assertion for each element of the slice and to check if it's a HttpError?

发自我的 iPhone

**Comment by parnurzeal** [comment]
I would just do type assertion as usual.
```
  for i := 0; i < len(errs); i++ {
    if v, ok := errs[i].(*E1); ok {
      fmt.Println(v)
    }
    if v, ok := errs[i].(*E2); ok {
      fmt.Println(v)
    }
  }
```
